from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List
import logging

from app.core.database import get_db
from app.core.security import verify_api_key
from app.models.trading import AlertResponse
from app.services.sentinel_service import SentinelService

router = APIRouter()
logger = logging.getLogger(__name__)

@router.get("/sentinel/alerts", response_model=List[AlertResponse], dependencies=[Depends(verify_api_key)])
async def get_alerts(
    unread_only: bool = False,
    alert_type: str = None,
    limit: int = 50,
    db: AsyncSession = Depends(get_db)
):
    """
    Get proactive alerts generated by the Sentinel.
    These alerts link current news to your past trading history.
    """
    try:
        service = SentinelService(db)
        alerts = await service.get_alerts(unread_only=unread_only, alert_type=alert_type, limit=limit)
        
        return [
            AlertResponse(
                id=a.id,
                title=a.title,
                message=a.message,
                alert_type=a.alert_type,
                similarity_score=a.similarity_score,
                is_read=a.is_read,
                timestamp=a.timestamp,
                matched_activity_id=a.matched_activity_id
            )
            for a in alerts
        ]
    except Exception as e:
        logger.error(f"Failed to fetch alerts: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/sentinel/alerts/{alert_id}/read", dependencies=[Depends(verify_api_key)])
async def mark_alert_read(
    alert_id: int,
    db: AsyncSession = Depends(get_db)
):
    """Mark an alert as read."""
    try:
        service = SentinelService(db)
        await service.mark_as_read(alert_id)
        return {"status": "success"}
    except Exception as e:
        logger.error(f"Failed to mark alert read: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
